apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg
spec:
  replicas: 2
  selector:
    matchLabels:
      name: bg
  template:
    metadata:
      labels:
        name: bg
    spec:
      imagePullSecrets:
        - name: gar-secret
      containers:
        - name: bg
          image: us-central1-docker.pkg.dev/intrepid-axe-482904-f4/harness-repo/app:blue
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bg-svc
spec:
  selector:
    name: bg
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    protocol: "TCP"                
